name: Nightwatch Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: mkdir -p screens logs
    - run: npm install nightwatch@latest
    - run: sudo apt-get install xvfb
    - name: Display Browser Information
      run: |
        echo "Operating System: $(uname -s)"
        echo "GitHub Runner OS: ${{ runner.os }}"
        echo "GitHub Runner Label: ${{ runner.label }}"
        echo "Browser Version: $BROWSER_VERSION"

    - name: Set Browser Version
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          BROWSER_VERSION=$(Get-Item "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe").VersionInfo.FileVersion
        elif [ "${{ runner.os }}" == "Linux" ]; then
          BROWSER_VERSION=$(edge --version)
        else
          BROWSER_VERSION=$(mdls -name kMDItemVersion /Applications/Microsoft\ Edge.app | awk '{print $NF}')
        fi
        echo "BROWSER_VERSION=$BROWSER_VERSION" >> $GITHUB_ENV
    - name: Download EdgeDriver
      run: |
          curl -L -o msedgedriver_linux64.zip "https://msedgedriver.azureedge.net/119.0.2151.72/edgedriver_linux64.zip"
          7z x msedgedriver_linux64.zip           
          unzip -o msedgedriver_linux64.zip        
          mv msedgedriver.exe ./node_modules/.bin/   
          chmod +x ./node_modules/.bin/msedgedriver.exe
    - name: Install dependencies
      run: npm install puppeteer-core

    - name: Get Edge Version
      id: get_edge_version
      run: |
        EDGE_VERSION=$(node -e "console.log(require('puppeteer-core/package.json').version)")
        echo "EDGE_VERSION=$EDGE_VERSION" >> $GITHUB_ENV

    - name: Display Edge Version
      run: |
        echo "Edge Version is $EDGE_VERSION"
    - name: Run Nightwatch tests
      run: |  
         ls -l ./node_modules/.bin/msedgedriver.exe
         npm list nightwatch
         echo $PWD
         npm test
    - name: "Publish test results"
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './tests_output/nightwatch-html-report'
        keep_files: true
        user_name: "gravityvi"
        user_email: "ravisawlani04@gmail.com"

    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: Screenshots
        path: screens/
        retention-days: 1

    - name: Display structure of downloaded files
      if: always()
      run: ls -R
      working-directory: screens/

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: Logs
        path: logs/
        retention-days: 1

    - name: Display structure of log files
      if: always()
      run: ls -R
      working-directory: logs/
